# Generated by Django 2.2.4 on 2020-11-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2App', '0004_restaurantpicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantPicture',
        ),
    ]
