# Generated by Django 2.2.4 on 2020-11-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project2App', '0005_delete_restaurantpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurantPictures', to='project2App.Restaurant'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userPictures', to='project2App.User'),
        ),
    ]
