# Generated by Django 2.2.4 on 2020-11-28 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project2App', '0008_auto_20201127_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='restaurantProfilePic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurantProfilePic', to='project2App.Restaurant'),
        ),
    ]
