# Generated by Django 2.2.4 on 2020-11-29 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project2App', '0009_image_restaurantprofilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='restaurantProfilePic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restaurantProfilePic', to='project2App.Restaurant'),
        ),
    ]
